Repository UniLogin/UniLogin, pull requests merged in 2020-05, with the labels that each got.

#2218 Enabling free messaging in sdk
  universal-login-sdk/src/api/wallet/DeployedWallet.ts
  universal-login-sdk/src/integration/http/RelayerApi.ts
  universal-login-sdk/test/api/wallet/DeployedWallet.int.test.ts
  universal-login-sdk/test/core/services/WalletService.int.test.ts
Labels: auto-merge

#2227 Remove redundant build
  .circleci/config.yml
  universal-login-ops/package.json
Labels: auto-merge

#2232 Rename universal login sdk && update link to repository
  package.json
  universal-login-react/src/core/models/ReactModalContext.ts
  universal-login-react/src/playground/App.tsx
  universal-login-react/src/ui/PlaygroundUtils/mockNotifications.ts
  universal-login-react/src/ui/Transfer/Amount/TransferDropdown.tsx
  universal-login-react/src/ui/Transfer/Amount/TransferDropdownItem.tsx
  universal-login-react/src/ui/Transfer/Transfer.tsx
  universal-login-react/src/ui/WalletSelector/EnsNamePicker.tsx
  universal-login-react/src/ui/WalletSelector/WalletSelector.tsx
  universal-login-react/src/ui/commons/Asset.tsx
  universal-login-react/src/ui/commons/FeatureFlag.tsx
  universal-login-react/src/ui/commons/GasPrice/GasPrice.tsx
  universal-login-react/test/helpers/mockSdkPrices.ts
  universal-login-react/test/ui/FreeOnboarding.test.tsx
  universal-login-sdk/src/api/FutureWalletFactory.ts
  universal-login-sdk/src/api/sdk.ts
  universal-login-sdk/src/api/wallet/ConnectingWallet.ts
  universal-login-sdk/src/api/wallet/DeployedWallet.ts
  universal-login-sdk/src/api/wallet/DeployingWallet.ts
  universal-login-sdk/src/api/wallet/FutureWallet.ts
  universal-login-sdk/src/core/services/WalletSerializer.ts
  universal-login-sdk/src/core/services/WalletService.ts
  universal-login-sdk/src/core/services/validations/RecipientValidator.ts
  universal-login-sdk/src/core/utils/getTargetAddress.ts
  universal-login-sdk/src/index.ts
  universal-login-sdk/test/api/sdk - connecting.test.ts
  universal-login-sdk/test/api/sdk - counterfactual.test.ts
  universal-login-sdk/test/api/sdk - events.test.ts
  universal-login-sdk/test/api/sdk.test.ts
  universal-login-sdk/test/api/wallet/DeployedWallet.int.test.ts
  universal-login-sdk/test/api/wallet/FutureWallet.test.ts
  universal-login-sdk/test/core/observers/AuthorisationObserver.int.test.ts
  universal-login-sdk/test/core/observers/BalanceObserver.unit.test.ts
  universal-login-sdk/test/core/observers/WalletEventsObserverFactory.int.test.ts
  universal-login-sdk/test/core/services/TransferService.int.test.ts
  universal-login-sdk/test/core/services/WalletService.int.test.ts
  universal-login-sdk/test/core/services/validations/RecipientValidator.ts
  universal-login-sdk/test/core/utils/getTargetAddress.test.ts
  universal-login-sdk/test/fixtures/basicSDK.ts
  universal-login-sdk/test/helpers/createDeployedWallet.ts
  universal-login-sdk/test/helpers/setupSdk.ts
  universal-login-wallet/src/ui/createServices.ts
  universal-login-wallet/test/integration/services/LoginServices.test.ts
  universal-login-web3/src/ULWeb3Provider.ts
  universal-login-web3/src/ui/react/ULWeb3Root.tsx
Labels: auto-merge

#2234 Extract NoRefundGasPrice
  universal-login-react/src/ui/commons/GasPrice/GasPrice.tsx
  universal-login-react/src/ui/commons/GasPrice/NoRefundGasPrice.tsx
Labels: auto-merge

#2240 Increase mineable factory timeout in tests
  universal-login-commons/src/core/constants/test.ts
Labels: auto-merge

#2235 Extract getPrices from SDK to commons
  universal-login-commons/src/core/services/TokenPricesService.ts
  universal-login-commons/src/index.ts
  universal-login-commons/test/core/services/TokenPricesService.test.ts
  universal-login-react/src/core/utils/getMinimalAmountForFiatProvider.ts
  universal-login-react/test/core/utils/getMinimalAmountForFiatProvider.test.ts
  universal-login-sdk/src/api/sdk.ts
  universal-login-sdk/src/core/observers/PriceObserver.ts
  universal-login-sdk/src/index.ts
  universal-login-sdk/src/integration/http/tokensPrices.ts
  universal-login-sdk/test/mock/PriceObserver.ts
Labels: auto-merge

#2217 Add E2E test for topup modal
  universal-login-wallet/cypress/integration/walletRoundTrip.test.ts
  universal-login-wallet/cypress/support/index.js
  universal-login-wallet/cypress/support/topupCommands.ts
Labels: auto-merge

#2252 Preparations for validate futureWallet's gasToken
  universal-login-commons/src/core/constants/test.ts
  universal-login-commons/src/core/utils/safeMultiply.ts
  universal-login-commons/src/index.ts
  universal-login-commons/test/core/utils/safeMultiply.test.ts
  universal-login-relayer/test/core/services/execution/PendingMessages.test.ts
  universal-login-sdk/test/core/services/GasModeService.test.ts
Labels: auto-merge

#2243 Add e2e test for send modal
  universal-login-wallet/cypress/integration/walletRoundTrip.test.ts
  universal-login-wallet/cypress/support/topupCommands.ts
Labels: WIP

#2255 Update gas price
  universal-login-commons/src/core/constants/test.ts
  universal-login-commons/test/integration/ethereum/validators/SufficientBalanceValidator.test.ts
  universal-login-contracts/test/contracts/Wallet/WalletImplementation.test.ts
  universal-login-react/test/ui/Dashboard.test.tsx
  universal-login-relayer/test/e2e/deploy.test.ts
  universal-login-relayer/test/e2e/future.test.ts
  universal-login-relayer/test/integration/ethereum/WalletService.test.ts
  universal-login-relayer/test/testhelpers/setupWalletService.ts
  universal-login-wallet/test/pages/LoginPage.ts
  universal-login-wallet/test/testhelpers/ServicesUnderTests.ts
  universal-login-wallet/test/testhelpers/setupUI.tsx
  universal-login-wallet/test/ui/CreateAccount.test.tsx
  universal-login-wallet/test/ui/Transfer.test.tsx
  universal-login-wallet/test/ui/connect.test.tsx
Labels: auto-merge

#2253 Introduce GasTokenValidator
  universal-login-commons/src/core/utils/safeMultiply.ts
  universal-login-commons/test/core/utils/safeMultiply.test.ts
  universal-login-relayer/src/core/services/FutureWalletHandler.ts
  universal-login-relayer/src/core/services/validators/GasTokenValidator.ts
  universal-login-relayer/src/core/utils/errors.ts
  universal-login-relayer/src/http/relayers/Relayer.ts
  universal-login-relayer/test/core/services/FutureWalletHandler.test.ts
  universal-login-relayer/test/core/services/validators/GasTokenValidator.test.ts
Labels: auto-merge

#2270 Rename universal-login -> unilogin
  universal-login-ops/bin/unilogin
  universal-login-ops/package.json
  universal-login-ops/test/ENS/DomainRegistrar.test.ts
Labels: auto-merge

#2280 Remove unused component - Accordion
  universal-login-react/src/index.ts
  universal-login-react/src/playground/App.tsx
  universal-login-react/src/ui/Settings/Accordion.tsx
  universal-login-react/src/ui/Settings/ManageDevices.tsx
  universal-login-react/src/ui/Settings/Settings.tsx
  universal-login-react/src/ui/commons/NavigationColumn.tsx
  universal-login-react/src/ui/styles/accordion.sass
  universal-login-react/src/ui/styles/accordionDefaults.sass
  universal-login-react/src/ui/styles/settings.sass
  universal-login-react/src/ui/styles/settingsDefaults.sass
Labels: auto-merge

#2282 Improve getMinimalAmount
  universal-login-react/src/core/utils/getMinimalAmountForFiatProvider.ts
  universal-login-react/test/core/utils/getMinimalAmountForFiatProvider.test.ts
Labels: auto-merge

#2283 Introduce bigNumberifyDecimal
  universal-login-commons/src/core/utils/bigNumbers.ts
  universal-login-commons/src/index.ts
  universal-login-commons/test/core/utils/bigNumbers.test.ts
Labels: auto-merge

#2281 Update selector for cypress test
  universal-login-wallet/cypress/support/loginAppCommands.ts
Labels: auto-merge

#2285 Adjust TopUp component to refund with token
  universal-login-react/src/core/utils/getMinimalAmountForFiatProvider.ts
  universal-login-react/src/ui/TopUp/ChooseTopUpMethod.tsx
  universal-login-react/src/ui/TopUp/ChooseTopUpMethodHeader.tsx
  universal-login-react/src/ui/TopUp/ChooseTopUpToken.tsx
  universal-login-react/src/ui/TopUp/Fiat/AmountInput.tsx
  universal-login-react/src/ui/TopUp/Fiat/FiatFooter.tsx
  universal-login-react/src/ui/TopUp/Fiat/TopUpDetails.tsx
  universal-login-react/src/ui/TopUp/Fiat/TopUpWithFiat.tsx
  universal-login-react/src/ui/TopUp/TopUp.tsx
  universal-login-react/src/ui/TopUp/TopUpRadio.tsx
  universal-login-react/src/ui/TopUp/TopUpWithCrypto.tsx
  universal-login-sdk/src/api/wallet/FutureWallet.ts
Labels: auto-merge

#2286 Remove unnecessary wrapper from ErrorMessage
  universal-login-react/src/ui/BackupCodes/BackupCodes.tsx
  universal-login-react/src/ui/UFlow/Devices/Devices.tsx
  universal-login-react/src/ui/commons/ErrorMessage.tsx
  universal-login-react/src/ui/styles/themes/Jarvis/components/text/errorMessageThemeJarvis.sass
  universal-login-react/src/ui/styles/themes/Jarvis/modalThemeJarvis.sass
  universal-login-wallet/src/ui/react/Modals/Transfer/ModalTransfer.tsx
Labels: auto-merge

#2276 Remove unnecessary wrapper from Transfer
  universal-login-react/src/ui/Transfer/Transfer.tsx
  universal-login-react/src/ui/styles/base/transfer.sass
  universal-login-react/src/ui/styles/themes/Jarvis/components/currencyDropdownThemeJarvis.sass
  universal-login-react/src/ui/styles/themes/Jarvis/transferThemeJarvis.sass
  universal-login-react/src/ui/styles/themes/Legacy/transferThemeLegacy.sass
  universal-login-react/src/ui/styles/transferDefaults.sass
  universal-login-wallet/src/ui/styles/layout/_dashboard.sass
Labels: auto-merge

#2294 Add ChooseTopUpToken in wallet
  universal-login-react/src/core/utils/errors.ts
  universal-login-react/src/index.ts
  universal-login-react/src/playground/App.tsx
  universal-login-react/src/playground/config.ts
  universal-login-react/src/ui/Onboarding/OnboardingSteps.tsx
  universal-login-react/src/ui/TopUp/ChooseTopUpToken.tsx
  universal-login-wallet/src/ui/react/CreateAccount/CreateAccount.tsx
  universal-login-wallet/test/pages/LoginPage.ts
Labels: auto-merge

#2278 Remove unnecessary wrapper from ModalTransfer
  universal-login-react/src/ui/Transfer/ModalTransfer.tsx
Labels: reviewing

#2279 Remove unnecessary wrapper from WaitingForOnRampProvider
  universal-login-react/src/ui/Onboarding/OnboardingSteps.tsx
  universal-login-react/src/ui/TopUp/Fiat/TopUpWithFiat.tsx
  universal-login-react/src/ui/TopUp/Fiat/WaitingForOnRampProvider.tsx
  universal-login-react/src/ui/TopUp/TopUp.tsx
  universal-login-react/src/ui/styles/footerSection.sass
  universal-login-wallet/src/ui/react/CreateAccount/CreateTopUp.tsx
  universal-login-wallet/src/ui/styles/layout/_login.sass
Labels: auto-merge

#2290 Remove unnecessary wrapper from ManualDashboard modal
  universal-login-react/src/ui/UFlow/ManualDashboard.tsx
Labels: auto-merge

#2293 Delete getStyleForTopLevelComponent function
  universal-login-react/src/core/utils/getStyleForTopLevelComponent.ts
Labels: auto-merge

#2308 Extract gasPriceOracleMock
  universal-login-commons/src/core/constants/test.ts
  universal-login-commons/src/index.ts
  universal-login-commons/test/helpers/mocks/gasPriceOracle.ts
  universal-login-commons/test/index.ts
  universal-login-relayer/test/core/services/validators/GasTokenValidator.test.ts
  universal-login-relayer/test/integration/ethereum/WalletService.test.ts
  universal-login-relayer/test/testhelpers/setupWalletContractService.ts
  universal-login-relayer/test/testhelpers/setupWalletService.ts
  universal-login-sdk/test/core/services/GasModeService.test.ts
Labels: auto-merge

#2314 Remove .universal-login-default's selectors
  universal-login-react/src/ui/Modals/ModalWrapper.tsx
  universal-login-react/src/ui/styles/base/progress-bar.sass
  universal-login-react/src/ui/styles/base/udashboard.sass
  universal-login-react/src/ui/styles/themes/Jarvis/modalThemeJarvis.sass
  universal-login-react/src/ui/styles/themes/Legacy/disconnectAccountThemeLegacy.sass
  universal-login-react/src/ui/styles/themes/Legacy/udashboardThemeLegacy.sass
  universal-login-react/src/ui/styles/themes/UniLogin/disconnectAccountThemeUniLogin.sass
  universal-login-web3/src/ui/react/Web3PickerComponent.tsx
  universal-login-web3/src/ui/react/common/GlobalStyle.ts
  universal-login-web3/src/ui/styles/index.css
Labels: auto-merge

#2318 Update GasTokenValidator
  universal-login-commons/src/index.ts
  universal-login-relayer/src/core/services/validators/GasTokenValidator.ts
  universal-login-relayer/test/core/services/validators/GasTokenValidator.test.ts
Labels: auto-merge

#2319 Improve BackupCodes appearance
  universal-login-react/src/ui/UFlow/Devices/ConnectedDeviceView.tsx
Labels: auto-merge

#2312 Validate message
  universal-login-contracts/test/helpers/ExampleMessages.ts
  universal-login-relayer/src/core/services/execution/messages/MessageHandler.ts
  universal-login-relayer/test/core/services/execution/messages/MessageHandler.test.ts
  universal-login-relayer/test/core/services/execution/messages/MultiSignatureExecute.test.ts
  universal-login-relayer/test/e2e/wallet.test.ts
  universal-login-sdk/test/api/sdk - events.test.ts
  universal-login-sdk/test/api/wallet/DeployedWallet.int.test.ts
  universal-login-sdk/test/core/services/TransferService.int.test.ts
  universal-login-sdk/test/fixtures/basicSDK.ts
  universal-login-web3/test/ULWeb3Provider.test.ts
Labels: auto-merge

#2337 Make spinner centered on devices modal
  universal-login-react/src/ui/styles/base/devices.sass
Labels: auto-merge

#2338 Add overflow for signMessage
  universal-login-web3/src/ui/react/Confirmation/SignConfirmation.tsx
Labels: auto-merge
